BlogApp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name="blogs"

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('blog_details/<int:pk>', views.BlogDetailView.as_view(), name='details'),
    path('create_posts/', views.CreateBlogPostView.as_view(), name='create'),
    path('edit_posts/<int:id>', views.EditBlogPostView.as_view(), name='edit_post'),
]


if settings.DEBUG:
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

users/urls.py
from django.urls import path, include
from . import views

app_name="users"

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.RegisterViewPage.as_view(), name="register"),

]

blogs/models.py
from django.db import models
from uuid import uuid4
from ckeditor.fields import RichTextField
from django.urls import reverse
from users.models import User

class BlogPost(models.Model):
    id = models.IntegerField(editable=False, primary_key=True, default=uuid4)
    title = models.CharField(max_length=150)
    text = RichTextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateField(auto_now_add=True)
    class Meta:
        verbose_name = ("Blog Post")
        verbose_name_plural = ("Blog Posts")

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse("blogs:home")
    

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
# Create your models here.

class UserManger(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given email must be set.")
        email = self.normalize_email(email=email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self.db)
        return user
    
    def create_user(self, email, password=None, **extra_feilds):
        extra_feilds.setdefault('is_staff', False)
        extra_feilds.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_feilds)

    def create_superuser(self, email, password, **extra_feilds):
        extra_feilds.setdefault('is_staff', True)
        extra_feilds.setdefault('is_superuser', True)

        if extra_feilds.get('is_superuser') is True:
            get_user_model().objects.filter(is_superuser=True).update(
            first_name="Velder", last_name="Mont"
        )

        if extra_feilds.get('is_staff') is not True:
            raise ValueError("Superuser must have is_staff=True")
        if extra_feilds.get('is_superuser') is not True:
            raise ValueError("Superuser must have is_superuser=True")

        return self._create_user(email, password, **extra_feilds)

class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManger()

blogs/forms.py
from .models import BlogPost
from django import forms

class CreatePost(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ('title', 'text')

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import User

class CustomUserCreation(UserCreationForm):
    User = get_user_model()
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('first_name','last_name','email', 'password1', 'password2')

blogs/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from .models import BlogPost
from .forms import CreatePost
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import Http404


class HomePageView(ListView):
    template_name = "index.html"
    model = BlogPost
    context_object_name = "blogs"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_data"] = self.model.objects.filter(owner=self.request.user.id).order_by('date_added')
        return context
    


class BlogDetailView(DetailView):
    template_name = "details.html"
    def get(self, request,pk):
        blog_text = get_object_or_404(BlogPost, id=pk)
        blog_text_data = blog_text.text
        num_visit = request.session.get('num_visit', 0)
        request.session['num_visit'] = num_visit + 1
        
        if request.user.is_authenticated and blog_text.owner != request.user:
            raise Http404

        context = {
            'title': f"BlogDetails/{BlogPost.objects.get(id=pk).title}",
            'id': blog_text,
            'blog_text': blog_text_data,
            'num_visit': num_visit
        }
        return render(request,self.template_name, context)

@method_decorator(login_required, name="dispatch")
class CreateBlogPostView(CreateView):
    model = BlogPost
    template_name = "create_post.html"
    form_class = CreatePost

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)
    
    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        if form.is_valid():
            return self.form_valid(form, **kwargs)
        else:
            return self.form_invalid(form, **kwargs)

@method_decorator(login_required, name="dispatch")
class EditBlogPostView(UpdateView):
    template_name = "edit_post.html"
    form_class = CreatePost
    queryset = BlogPost.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(BlogPost, id=id_)

    def form_valid(self, form):
        if BlogPost.objects.filter(owner=self.request.user):
            form.save()
        else:
            raise Http404
        return super().form_valid(form)
    
    def get_success_url(self):
        return "/"

users/views.py
from django.views.generic import CreateView
from .forms import CustomUserCreation
from django.shortcuts import redirect, render
from django.contrib.auth import login

class RegisterViewPage(CreateView):
    template_name = "registration/register.html"
    form_class = CustomUserCreation
    
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form':form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            email = form.cleaned_data.get('email')
            user.email = email
            user.save()
            login(request,user)
            return redirect("blogs:home")
        return super().post(request, self.template_name, {'form': form})
    

    

blogs/templates/base.html
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
    {% if title %}
      {{ title }}
        {% else %}
            My Blogs
      {% endif %}
    </title>
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include "includes/nav.html" %}


    <div class="container">
    {% block content %}
    </div>
    {% endblock content %}
    
    {% block footer %}
    
    {% endblock footer %}
    
    {% bootstrap_javascript %}
</body>
</html>

blogs/templates/create_post.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button type="submit" content="Post" button_class="btn-lg btn-primary"  %}
    </form>
{% endblock content %}

blogs/templates/details.html
{% extends "base.html" %}

{% block content %}
    <p class="lead">Page Visited: {{num_visit}}</p>
    <a class="btn btn-primary-outline" href="{% url 'blogs:edit_post' id.id %}">Edit</a>
    <br/>
    {{blog_text| safe}}
{% endblock content %}

blogs/templates/edit_post.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
    <h4 class="display-4 text-center">Update Data</h4>
    <hr />
    <form action="" method="post">
        {% csrf_token %}
        {%  bootstrap_form form  %}
        {% bootstrap_button content="Update" type="submit" button_class="btn-lg btn-success" %}
    </form>

{% endblock content %}

blogs/templates/includes/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'blogs:home' %}">My Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'blogs:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Projects</a>
          </li>
        </ul>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if not user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
              </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="">Welcome, {{user.first_name}} {{user.last_name}}</a>
            </li>
          {% endif %}
          
        </ul>
      </div>
    </div>
  </nav>

blogs/templates/index.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
      <h4 class="display-4 text-center">My Blogs<br/><a class="btn btn-dark-outline" href="{% url 'blogs:create' %}">Create a Post</a></h4>
    <hr />
    {% if user.is_authenticated %}
    {% for blog_header in user_data %}
    <div class="col-md-6">
    <div class="card w-75 m-2">
        <div class="card-body">
          <h5 class="card-title" style="font-size:22px;">{{blog_header.title}}</h5>
          <p class="lead">{{ blog_header.date_added }}</p>
          <div class="d-flex">
            <p class="badge text-primary">Added By:{{ blog_header.owner.first_name }} {{blog_header.owner.last_name}} </p>
            <a href="{% url 'blogs:details' blog_header.pk %}" class="btn btn-primary">Read Now</a>
          </div>
        </div>
      </div>
    </div>
{% endfor %}
    {% else %}
    {% for blog in blogs %}
    <div class="col-md-6">
    <div class="card w-75 m-2">
        <div class="card-body">
          <h5 class="card-title" style="font-size:22px;">{{blog.title}}</h5>
          <p class="lead">{{ blog.date_added }}</p>
          <div class="d-flex">
            <p class="badge text-primary">Added By:{{ blog.owner.first_name }} {{blog.owner.last_name}} </p>
            <a href="{% url 'blogs:details' blog.pk %}" class="btn btn-primary">Read Now</a>
          </div>
        </div>
      </div>
    </div>
{% endfor %}
    {% endif %}
    </div>
{% endblock content %}